url: https://openc3.com
baseurl:
markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

openc3: https://github.com/openc3/cosmos
repository: https://github.com/openc3/openc3.com

plugins:
  - jekyll-toc
  - jekyll-redirect-from

# Collections are specified as a name and correspond to a directory
# that consists of the name prepended with '_', e.g. _docs
# Collections are accessed in Jekyll via site.docs or site['docs']
# Note the collection name is available from the page, e.g. page.collection
# Thus you can do site[page.collection] to access the collection
collections:
  docs_v5:
    output: true
    permalink: docs/v5/:name
  docs_enterprise:
    output: true
    permalink: docs/enterprise/:name

# Default collection
default: v5

exclude:
  - Gemfile
  - Rakefile

# These are used by the plugins to generate content
openc3_root_v5: ../openc3/openc3
openc3_meta_path: data/config
openc3_tool_path: install/tools
